### ISSUE TITLE
Does Evergreen support Dependabot configuration for private registries? 

### ISSUE THREAD

**Issue by charliew33** [github/evergreen#199]
### Is your feature request related to a problem?

When setting up `dependabot.yml` files I typically need to set up at least one private registry, depending on the ecosystems being used. Is there a way to configure Evergreen to include the private registry config in the deployed `dependabot.yml` files? 

### Describe the solution you'd like

Ideally I'd like to be able to configure that for particular ecosystems, Evergreen should include the private registry config in the `dependabot.yml`, for example for npm:

```
version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    username: octocat
    password: ${{secrets.MY_NPM_PASSWORD}}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-npmjs
    schedule:
      interval: "weekly"
```
