### ISSUE TITLE
Monthly schedule used for weekly workflow examples

### ISSUE THREAD

**Issue by lelia** [github/evergreen#51]
In the [basic](https://github.com/github/evergreen?tab=readme-ov-file#basic) and [advanced](https://github.com/github/evergreen?tab=readme-ov-file#advanced) workflow examples, a weekly cadence is implied through the workflow names and the script to define `$env.one_week_ago`, but a [monthly cadence](https://crontab.guru/#3_2_1_*_*) is defined in the `schedule` trigger section:

```yaml
name: Weekly dependabot checks
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *' 
```
