### ISSUE TITLE
Support grouping of dependencies updates

### ISSUE THREAD

**Issue by gbrindisi** [github/evergreen#53]
Hi, 
it would be useful to have the option to automatically enable some basic [grouping](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) for dependency updates from the start, since dependabot can become quite noisy.

A barebone configuration with grouping enabled could be the one using the default production/development groups:
```
---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
        interval: 'weekly'
    groups:
        production-dependencies:
            dependency-type: 'production'
        development-dependencies:
            dependency-type: 'development'
```
