### ISSUE TITLE
TypeError: fromisoformat: argument must be str

### ISSUE THREAD

**Issue by stevexiong-hennepin** [github/evergreen#92]
### Describe the bug

I'm testing this out for use. I'm getting the below error running on ubuntu-latest GitHub runner. 

Traceback (most recent call last):
  File "/action/workspace/evergreen.py", line 361, in <module>
    main()  # pragma: no cover
    ^^^^^^
  File "/action/workspace/evergreen.py", line 83, in main
    if is_repo_created_date_before(repo.created_at, created_after_date):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/action/workspace/evergreen.py", line [16](https://github.com/HennepinCounty/cloudops-dev-test/actions/runs/8638172575/job/23682036775#step:5:17)4, in is_repo_created_date_before
    repo_created_at_date = datetime.fromisoformat(repo_created_at).replace(tzinfo=None)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str

### To Reproduce

1. Copied the basic example workflow from readme
2. Updated 'Run evergreen action' step to the below
```
      - name: Run evergreen action
        uses: github/evergreen@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: "myorg/myrepo"
          FILTER_VISIBILITY: "private,internal"
```
3. Run workflow manually through GitHub Actions page

### Expected behavior

As state in readme, it open issue/PR in the specified repo.

### Additional context

I did adding env CREATED_AFTER_DATE and hardcoded "2020-01-01" as value. I got the same error. 

I did see the closed issue https://github.com/github/evergreen/issues/82, and the error appears to committed code from the pr https://github.com/github/evergreen/pull/83 that closed that issue.
